name: My framework

on:
   schedule:
   - cron: 00 18 * * *
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running My Framework with maven
      run: mvn test -X -Dbrowser=chrome -DisHeadless=ture -DisLambda=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test logs
       path: logs/
       
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test Reports
       path: reports.html

    - name: Test execution Status
      run: echo "Test Exeuction complted'


